package ast;

public enum NodeKind {
  EXPRESION, DECLARACION, PUNTOYCOMA, AMBITO, IF, ELSIF, ELSE, NEW, TIPO, SWITCH, CASE, WHILE, FOR, RETURN, PRINTS, VALOR, ASIGNACION, SCANS, TYPEDEF, UNIONAMBITO, VACIO, DEFINICION}
