package ast.Expresiones;

public enum KindE {
    ACCCAMPO, CONJUNCION, DISTINTO, DISYUNCION, DIVISION, IGUAL, MAYIGUAL, MAYQ, MENIGUAL, MENQ, PROD, SUMA, ACCPUN, MAS, MASMAS, MENOS, MENOSMENOS, NEG, ACCFUN, CONST, RESTA, ACCARRAY
}
