
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 20 20:20:17 CEST 2024
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 18;
  public static final int LLCIERRE = 10;
  public static final int CCIERRE = 8;
  public static final int PCIERRE = 6;
  public static final int ELSIF = 36;
  public static final int CASE = 32;
  public static final int CAP = 7;
  public static final int OPPUNTO = 15;
  public static final int INT = 41;
  public static final int FOR = 30;
  public static final int MENORIGUAL = 24;
  public static final int MAYORQUE = 23;
  public static final int IGUAL = 17;
  public static final int OPASTERISCO = 14;
  public static final int LLAP = 9;
  public static final int BOOL = 42;
  public static final int CLASS = 38;
  public static final int DIV = 4;
  public static final int OPMASMAS = 46;
  public static final int MAIN = 50;
  public static final int IF = 35;
  public static final int MAYORIGUAL = 25;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int RETURN = 34;
  public static final int PRINTS = 27;
  public static final int TRUE = 43;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int NEGACION = 19;
  public static final int MENOS = 3;
  public static final int OPMENOSMENOS = 47;
  public static final int VOID = 40;
  public static final int PCOMA = 11;
  public static final int SWITCH = 31;
  public static final int MENORQUE = 22;
  public static final int ENT = 49;
  public static final int PAP = 5;
  public static final int ELSE = 37;
  public static final int IDEN = 48;
  public static final int WHILE = 29;
  public static final int DEFAULT = 33;
  public static final int CONJUNCION = 20;
  public static final int DISYUNCION = 21;
  public static final int FALSE = 44;
  public static final int NULLPTR = 45;
  public static final int STRUCT = 39;
  public static final int SCANS = 28;
  public static final int OPPASOVALOR = 16;
  public static final int MAS = 2;
}

