
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Mar 21 13:04:29 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int EOF = 0;
  
  public static final int IDEN = 1;
  public static final int ENT = 2;
  public static final int MAS = 3;
  public static final int MENOS = 4;
  public static final int DIV = 5;
  public static final int PAP = 6;
  public static final int PCIERRE = 7;
  public static final int CAP = 8;
  public static final int CCIERRE = 9;
  public static final int LLAP = 10;
  public static final int LLCIERRE = 11;
  public static final int PCOMA = 12;
  public static final int COMA = 13;
  
  public static final int ASIG = 14;
  public static final int OPASTERISCO = 15;
  public static final int OPPUNTO = 16;
  public static final int OPPASOVALOR = 17;
  public static final int IGUAL = 18;
  public static final int DISTINTO = 19;
  public static final int NEGACION = 20;
  public static final int CONJUNCION = 21;
  public static final int DISYUNCION = 22;
  public static final int MENORQUE = 23;
  public static final int MAYORQUE = 24;
  public static final int MENORIGUAL = 25;
  public static final int MAYORIGUAL = 26;
  public static final int NEW = 27;
  public static final int PRINTS = 28;
  public static final int SCANS = 29;
  
  public static final int WHILE = 30;
  public static final int FOR = 31;
  public static final int SWITCH = 32;
  public static final int CASE = 33;
  public static final int DEFAULT = 34;
  public static final int RETURN = 35;
  public static final int IF = 36;
  public static final int ELSIF = 37;
  public static final int ELSE = 38;
  
  public static final int CLASS = 39;
  public static final int STRUCT = 40;
  public static final int TYPEDEF = 41;
  public static final int INT = 42;
  public static final int BOOL = 43;
  public static final int TRUE = 44;
  public static final int FALSE = 45;
}

