
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 09 06:01:40 CEST 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 20;
  public static final int LLCIERRE = 12;
  public static final int CCIERRE = 10;
  public static final int PCIERRE = 8;
  public static final int ELSIF = 38;
  public static final int CASE = 34;
  public static final int CAP = 9;
  public static final int OPPUNTO = 17;
  public static final int INT = 43;
  public static final int FOR = 32;
  public static final int MENORIGUAL = 26;
  public static final int MAYORQUE = 25;
  public static final int IGUAL = 19;
  public static final int OPASTERISCO = 16;
  public static final int LLAP = 11;
  public static final int BOOL = 44;
  public static final int CLASS = 40;
  public static final int DIV = 6;
  public static final int OPMASMAS = 47;
  public static final int TYPEDEF = 42;
  public static final int IF = 37;
  public static final int MAYORIGUAL = 27;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int ASIG = 15;
  public static final int PRINTS = 29;
  public static final int TRUE = 45;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int COMA = 14;
  public static final int NEGACION = 21;
  public static final int MENOS = 5;
  public static final int OPMENOSMENOS = 48;
  public static final int PCOMA = 13;
  public static final int SWITCH = 33;
  public static final int MENORQUE = 24;
  public static final int ENT = 3;
  public static final int PAP = 7;
  public static final int ELSE = 39;
  public static final int IDEN = 2;
  public static final int WHILE = 31;
  public static final int DEFAULT = 35;
  public static final int CONJUNCION = 22;
  public static final int DISYUNCION = 23;
  public static final int FALSE = 46;
  public static final int STRUCT = 41;
  public static final int SCANS = 30;
  public static final int OPPASOVALOR = 18;
  public static final int MAS = 4;
}

